<?php
/*
*
* Author: Sherwin R. Terunez
* Contact: sherwinterunez@yahoo.com
*
* Description:
*
* App Module
*
* Date: November 13, 2015
*
*/

if(!defined('APPLICATION_RUNNING')) {
	header("HTTP/1.0 404 Not Found");
	die('access denied');
}

if(defined('ANNOUNCE')) {
	echo "\n<!-- loaded: ".__FILE__." -->\n";
}

$toolbars['app']['main'] = 	array(
	array(	"id"=>"dashboard",
			"type"=>"buttonSelect",
			"text"=>"Dashboard",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "dashboard",
			"opts"=>array(
				array(	"id"=>"dashboardmenu",
						"type"=>"obj",
						"text"=>"Menu1",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
						"tab_width" => 150,
						"multiple" => false,
						"module"=>"dashboard",
				),
		)
	),
	array(	"id"=>"load",
			"type"=>"button",
			"text"=>"Load",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "load",
	),
	array(	"id"=>"remittance",
			"type"=>"button",
			"text"=>"Remittance",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "remittance",
	),
	array(	"id"=>"encashment",
			"type"=>"button",
			"text"=>"Encashment",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "encashment",
	),
	array(	"id"=>"payables",
			"type"=>"button",
			"text"=>"Payables",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "payables",
	),
	array(	"id"=>"inventory",
			"type"=>"button",
			"text"=>"Inventory",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "inventory",
	),
	array(	"id"=>"contact",
			"type"=>"button",
			"text"=>"Contacts",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "contact",
	),
	array(	"id"=>"receivables",
			"type"=>"button",
			"text"=>"Receivables",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "receivables",
	),
	array(	"id"=>"discount",
			"type"=>"button",
			"text"=>"Discount",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "discount",
	),
	array(	"id"=>"setting",
			"type"=>"button",
			"text"=>"Setting",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "setting",
	),
	array(	"id"=>"tools",
			"type"=>"button",
			"text"=>"Tools",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "tools",
	),
	array(	"id"=>"reports",
			"type"=>"button",
			"text"=>"Reports",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "reports",
	),
	array(	"id"=>"messaging",
			"type"=>"buttonSelect",
			"text"=>"Messaging",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"module" => "messaging",
			"opts"=>array(
				array(	"id"=>"messagingcompose",
						"type"=>"obj",
						"text"=>"Compose",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
						"tab_width" => 150,
						"multiple" => false,
						"module"=>"messaging",
				),
		)
	),
	array(	"id"=>"management",
			"type"=>"buttonSelect",
			"text"=>"Security",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"opts"=>array(
				array(	"id"=>"useraccount",
						"type"=>"obj",
						"text"=>"User Accounts",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
						"tab_width" => 150,
						"multiple" => false,
						"module"=>"useraccount",
				),
		)
	),
	array(
		"id"=>"management",
		"type"=>"spacer",
	),
	/*array(	"id"=>"utilities",
			"type"=>"buttonSelect",
			"text"=>"Utilities",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"opts"=>array(
				array(	"id"=>"usermanagement",
						"type"=>"obj",
						"text"=>"User Management",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
						"tab_width" => 150,
						"multiple" => false,
						"module"=>"user",
				),
				array(
						"id"=>"utilitiessep1",
						"type"=>"separator",
				),
				array(	"id"=>"settings",
						"type"=>"obj",
						"text"=>"Settings",
						"img"=>"copy.gif",
						"imgdis"=>"copy.gif",
						"title"=>"Tooltip here",
						"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
						"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
				),
		)
	),
	array(
		"id"=>"utilities",
		"type"=>"spacer",
	),*/
	array(	"id"=>"title",
			"type"=>"text",
			"text"=>$applogin->fullname(),
	),
	array(	"id"=>"logout",
			"type"=>"button",
			"text"=>"Logout",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"tab_width" => 150,
			"multiple" => false,
	),
);

/*$toolbars['app']['usermanagement'] = array(
	array(	"id"=>"usermanagementnewroles",
			"type"=>"button",
			"text"=>"New Role",
			"img"=>"new.gif",
			"imgdis"=>"new_dis.gif",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"usermanagementnewuser",
			"type"=>"button",
			"text"=>"New User",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"usermanagementedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"usermanagementdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"usermanagementsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);*/

$toolbars['app']['useraccount'] = array(
	array(	"id"=>"useraccountnewrole",
			"type"=>"button",
			"text"=>"New Role",
			"img"=>"new.gif",
			"imgdis"=>"new_dis.gif",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"useraccountnewuser",
			"type"=>"button",
			"text"=>"New User",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"useraccountedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"edit.png",
			"imgdis"=>"edit.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"useraccountdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"useraccountsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"useraccountcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
	array(	"id"=>"useraccountrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"disk.png",
			"imgdis"=>"disk_dis.png",
			"title"=>"Tooltip here",
			"hidden"=>true,
			//"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			//"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
	),
);

$toolbars['app']['messaging'] = 	array(
	array(	"id"=>"messagingsendtooutbox",
			"type"=>"button",
			"text"=>"Send to Outbox",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingsendnow",
			"type"=>"button",
			"text"=>"Send Now",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingsendstart",
			"type"=>"button",
			"text"=>"Start",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingsendstop",
			"type"=>"button",
			"text"=>"Stop",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingcomposeto",
			"type"=>"button",
			"text"=>"Compose to",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingclone",
			"type"=>"button",
			"text"=>"Clone",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingresend",
			"type"=>"button",
			"text"=>"Resend",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingreply",
			"type"=>"button",
			"text"=>"Reply",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingforward",
			"type"=>"button",
			"text"=>"Forward",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingclear",
			"type"=>"button",
			"text"=>"Clear",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingimport",
			"type"=>"button",
			"text"=>"Import",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingexport",
			"type"=>"button",
			"text"=>"Export",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messagingoptions",
			"type"=>"button",
			"text"=>"Options",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"messaginginsertrow",
			"type"=>"button",
			"text"=>"Insert Row",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['load'] = 	array(
	array(	"id"=>"loadnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"loadedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"loaddelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"loadsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"loadcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"loadrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"loadapproved",
			"type"=>"button",
			"text"=>"Approved",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"loadmanually",
			"type"=>"button",
			"text"=>"Manually",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"loadcancelled",
			"type"=>"button",
			"text"=>"Cancelled",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"loadhold",
			"type"=>"button",
			"text"=>"Hold",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	/*array(	"id"=>"loadsep1",
			"type"=>"separator",
			"hidden"=>true,
	),*/
	array(	"id"=>"loadrefresh",
			"type"=>"spacer",
	),
	array(	"id"=>"loadfrom",
			"type"=>"text",
			"text"=>"From",
			"hidden"=>true,
	),
	array(	"id"=>"loaddatefrom",
			"type"=>"input",
			"text"=>"From",
			"pos"=>0,
			"value"=>"",
			"width"=>90,
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"loadto",
			"type"=>"text",
			"text"=>"To",
			"hidden"=>true,
	),
	array(	"id"=>"loaddateto",
			"type"=>"input",
			"text"=>"To",
			"pos"=>0,
			"value"=>"",
			"width"=>90,
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"loadfilter",
			"type"=>"button",
			"text"=>"Filter",
			//"img"=>"copy.gif",
			//"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['loadwindow'] = 	array(
	array(	"id"=>"loadwindownew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>false,
	),
);

$toolbars['app']['remittance'] = 	array(
	array(	"id"=>"remittancenew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"remittanceedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"remittancedelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"remittancesave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"remittancecancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"remittancerefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"remittancerefresh",
			"type"=>"spacer",
	),
	array(	"id"=>"remittancefrom",
			"type"=>"text",
			"text"=>"From",
			"hidden"=>true,
	),
	array(	"id"=>"remittancedatefrom",
			"type"=>"input",
			"text"=>"From",
			"pos"=>0,
			"value"=>"",
			"width"=>90,
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"remittanceto",
			"type"=>"text",
			"text"=>"To",
			"hidden"=>true,
	),
	array(	"id"=>"remittancedateto",
			"type"=>"input",
			"text"=>"To",
			"pos"=>0,
			"value"=>"",
			"width"=>90,
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"remittancefilter",
			"type"=>"button",
			"text"=>"Filter",
			//"img"=>"copy.gif",
			//"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['encashment'] = 	array(
	array(	"id"=>"encashmentnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"encashmentedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"encashmentdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"encashmentsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"encashmentcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"encashmentrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"encashmentrefresh",
			"type"=>"spacer",
	),
	array(	"id"=>"encashmentfrom",
			"type"=>"text",
			"text"=>"From",
			"hidden"=>true,
	),
	array(	"id"=>"encashmentdatefrom",
			"type"=>"input",
			"text"=>"From",
			"pos"=>0,
			"value"=>"",
			"width"=>90,
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"encashmentto",
			"type"=>"text",
			"text"=>"To",
			"hidden"=>true,
	),
	array(	"id"=>"encashmentdateto",
			"type"=>"input",
			"text"=>"To",
			"pos"=>0,
			"value"=>"",
			"width"=>90,
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"encashmentfilter",
			"type"=>"button",
			"text"=>"Filter",
			//"img"=>"copy.gif",
			//"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['payables'] = 	array(
	array(	"id"=>"payablesnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"payablesedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"payablesdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"payablessave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"payablescancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"payablesrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['inventory'] = 	array(
	array(	"id"=>"inventorynew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"inventoryedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"inventorydelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"inventorysave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"inventorycancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"inventoryrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"inventoryrecompute",
			"type"=>"button",
			"text"=>"Recompute",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(
		"id"=>"inventoryrecompute",
		"type"=>"spacer",
	),
	array(	"id"=>"inventorypause",
			"type"=>"button",
			"text"=>"Pause",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"inventoryresume",
			"type"=>"button",
			"text"=>"Resume",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"inventoryrestart",
			"type"=>"button",
			"text"=>"Restart",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"inventorysimpause",
			"type"=>"button",
			"text"=>"Pause",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"inventorysimresume",
			"type"=>"button",
			"text"=>"Resume",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"inventorysimrestart",
			"type"=>"button",
			"text"=>"Restart",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['receivables'] = 	array(
	array(	"id"=>"receivablesnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"receivablesedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"receivablesdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"receivablessave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"receivablescancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"receivablesrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['contact'] = 	array(
	array(	"id"=>"contactnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"contactedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"contactdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"contactsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"contactcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"contactrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['discount'] = 	array(
	array(	"id"=>"discountnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"discountedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"discountdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"discountsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"discountcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"discountrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['setting'] = 	array(
	array(	"id"=>"settingreset",
			"type"=>"button",
			"text"=>"Reset",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"settingnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"settingedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"settingclone",
			"type"=>"button",
			"text"=>"Clone",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"settingdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"settingsave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"settingcancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"settingrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"settinginsertrow",
			"type"=>"button",
			"text"=>"Insert Row",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['tools'] = 	array(
	array(	"id"=>"toolsnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"toolsedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"toolsdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"toolssave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"toolscancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"toolsrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['reports'] = 	array(
	array(	"id"=>"reportsnew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"reportsedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"reportsdelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"reportssave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"reportscancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
	array(	"id"=>"reportsrefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			"hidden"=>true,
	),
);

$toolbars['app']['sample'] = 	array(
	array(	"id"=>"samplenew",
			"type"=>"button",
			"text"=>"New",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			//"hidden"=>true,
	),
	array(	"id"=>"sampleedit",
			"type"=>"button",
			"text"=>"Edit",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			//"hidden"=>true,
	),
	array(	"id"=>"sampledelete",
			"type"=>"button",
			"text"=>"Delete",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			//"hidden"=>true,
	),
	array(	"id"=>"samplesave",
			"type"=>"button",
			"text"=>"Save",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			//"hidden"=>true,
	),
	array(	"id"=>"samplecancel",
			"type"=>"button",
			"text"=>"Cancel",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			//"hidden"=>true,
	),
	array(	"id"=>"samplerefresh",
			"type"=>"button",
			"text"=>"Refresh",
			"img"=>"copy.gif",
			"imgdis"=>"copy.gif",
			"title"=>"Tooltip here",
			"func"=>";(function(obj,id){srt.toolbar_func(obj,id);})(this,id);",
			"func_tab_close"=>";(function(obj,id){srt.tabbar_close_func(obj,id);})(this,id);",
			//"hidden"=>true,
	),
);
